version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  apicurio-registry:
    image: apicurio/apicurio-registry:3.0.7
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_PROFILE=prod
  apicurio-ui:
    image: apicurio/apicurio-registry-ui:3.0.7
    environment:
      - REGISTRY_API_URL=http://apicurio-registry:8080/apis/registry/v3/
    ports:
      - "8888:8080"